version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  rest-api:
    build: ./rest-api
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis

  graphql-api:
    build: ./graphql-api
    ports:
      - "6000:6000"
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - rest-api
      - graphql-api
